[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "palmsens-ui"
version = "0.1.0"
description = "app for running and visualizing palmSens measurements"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"PySide6",
	"PyPalmSens",
	"pyqtgraph",
	"pandas",
	"batterydf",
	"aurora-method-builder @ git+https://github.com/ahallgrenkemi/protocol-creator.git@8f358789cef56f97dc13d2284d428817e16be8c1",
	"pyserial"
]

[project.gui-scripts]
palmsens-ui = "src.main:main"

[tool.setuptools.packages.find]
include = ["src*"]
